#!/bin/bash

# run Clippy
cargo clippy --fix --allow-staged

# check the exit status of the previous command
if [ $? -ne 0 ]; then
    echo "Clippy check failed. Please fix formatting issues before committing."
    exit 1  # Exit with a non-zero status code to prevent the commit
fi

# run Rustfmt
cargo fmt --all

# check the exit status of the previous command
if [ $? -ne 0 ]; then
    echo "Rustfmt check failed. Please fix code issues before committing."
    exit 1  # Exit with a non-zero status code to prevent the commit
fi

# add the changes
git add .

# if all checks pass, the commit will proceed
exit 0
